import '@girs/gjs'
import '@girs/gjs/dom'

import '@girs/gio-2.0'
import '@girs/gtk-4.0'
import '@girs/gobject-2.0'
import '@girs/glib-2.0'
import '@girs/st-14'
import '@girs/gtop-2.0'
import '@girs/adw-1'
import '@girs/gdk-4.0'
import '@girs/shell-14'

import '@girs/gnome-shell/ambient'
import '@girs/gnome-shell/extensions/global'
import '@girs/gnome-shell/misc/ambient'